# Generated by Django 3.2.12 on 2022-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=40)),
                ('word_pieces', models.CharField(max_length=40)),
                ('frequent', models.IntegerField(default=0)),
            ],
        ),
    ]
